### PR TITLE
Add search feature

### PR DESCRIPTION
**Pull request by TheMisir**
This PR adds feature to support searching icons.

[Preview link](https://cupertino-icons.vercel.app/)

Click or tap on header to show & focus text box.

### CODE REVIEW

**Comment by guidezpl** [comment]
Nice filter idea. I would put this behind a visible search/filter icon, otherwise the feature won't be discoverable

**Comment by TheMisir** [comment]
> Nice filter idea. I would put this behind a visible search/filter icon, otherwise the feature won't be discoverable

Ok, I'll commit an update soon.

**Comment by TheMisir** [comment]
@guidezpl I've updated the website to always display search bar.

**Comment by xster** [comment]
oh very cool addition! Have you updated the preview site to include your new change? Affordance-wise, the default static UI can use more visual hints to show that the top area is clickable to turn into a search bar. You can use the search icon from the icon set itself to show a search button on the website :)

**Review by guidezpl — APPROVED** [review]

**Comment by TheMisir** [comment]
> oh very cool addition! Have you updated the preview site to include your new change? Affordance-wise, the default static UI can use more visual hints to show that the top area is clickable to turn into a search bar. You can use the search icon from the icon set itself to show a search button on the website :) 

Thanks for reviewing. I've updated the webpage as you've requested.

**Pull request merged**
