### PR TITLE
Updated back chevron codepoint to rounded version

### PR DESCRIPTION
**Pull request by jeremie-movify**
Rounded version matches San Francisco font

### CODE REVIEW

**Comment by jeremie-movify** [comment]
@googlebot I signed it!

**Comment by xster** [comment]
Superb. Thanks for your contribution! I was gonna mention a version bump too but you already did it :D

There's a bit of a size increase. I think there's a function in FontForge to cull unused codepoints. 
@shihaohong (or someone else in the team), would you mind patching this in and testing the gallery or some such to make sure everything's in good shape? 

This probably needs another follow-up PR to change the default create template version reference in pubspec.yaml

**Comment by xster** [comment]
We probably wouldn't want to add another .ttf file here either since it's a package that everyone that flutter creates needs to download. We would want to make sure it's something that everyone wants to use before adding.

**Comment by shihaohong** [comment]
I checked with `flutter_gallery` and a cursory glance at the back chevron update, as well as the existing icons in Cupertino --> Navigation the changes seem good.

**Comment by jeremie-movify** [comment]
> We probably wouldn't want to add another .ttf file here either since it's a package that everyone that flutter creates needs to download. We would want to make sure it's something that everyone wants to use before adding.

Thanks for pointing that out ; that was a boo-boo on my side, that duplicate was not meant to be pushed. I've removed it.

**Comment by jeremie-movify** [comment]
Good morning,

May I ask for an update on this PR ?

Thanks !

**Comment by xster** [comment]
Sorry for the delay. I'm out on paternity leave :)

A 120% size increment is still unusual (since it'll almost affect all Flutter users). Let's make sure we use all font size reducing mechanisms of fontforge (I think it lets you strip unused glyphs etc). I expect a pragmatic size increase to be ~5%.

**Comment by jeremie-movify** [comment]
Hi @xster,

thank you for your follow-up ; congratulations for your newborn !

I've re-generated the TTF font from FontForge, reaching an output size of 94 KB (the original file is 98 KB). Small improvement, but improvement nonetheless !

**Comment by xster** [comment]
Excellent, thanks so much for the tweaks.

**Pull request merged**
